config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='wiki/')),
    path('common/', include('common.urls')),
    path('wiki/', include('wiki.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'common.views.page_not_found'

wiki/urls.py
from django.urls import path
from .views import base_views, article_views, comment_views

app_name = 'wiki'

urlpatterns = [
    # views/base_views
    path('', base_views.index, name='index'),
    path('main_page/', base_views.main_page, name='main_page'),
    path('articles/', base_views.articles, name='articles'),
    path('search/', base_views.article_search, name='article_search'),
    path('new_article/', article_views.article_create, name='article_create'),

    path('<str:article_title>/', base_views.article, name='article'),
    path('<str:article_title>/edit/', article_views.article_edit, name='article_edit'),
    path('<str:article_title>/delete/', article_views.article_delete, name='article_delete'),
    path('<str:article_title>/new_comment/', comment_views.comment_create, name='comment_create'),
    path('<str:article_title>/comments/<str:comment_id>', comment_views.comment_delete, name='comment_delete'),
]

wiki/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length=200)
    parent_article = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    summary = models.CharField(max_length=200)
    content = models.TextField(max_length=100000)
    create_date = models.DateTimeField()
    recent_edit_date = models.DateTimeField()
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    is_public = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    # 해당 article 조회 url 리턴하는 method?


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    content = models.TextField(max_length=1000)
    create_date = models.DateTimeField()

wiki/forms.py
from django import forms
from wiki.models import Article, Comment
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

from .models import Article

# Article 최초 생성시 사용 form
class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article 
        fields = ['title', 'content']
        labels = {
            'title': '제목',
            'content': '본문',
        }

    def clean_title(self): # 중복 article 체크
        data = self.cleaned_data['title']
        try:
            article_with_same_title = Article.objects.get(title=data)
        except Article.DoesNotExist: # 중복 article이 존재하지 않음
            pass
        else: # 중복 article이 존재함
            raise forms.ValidationError(mark_safe("이미 동일한 title을 가진 article이 있습니다."))

        return data


# Article 수정시 사용 form
class ArticleEditForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['content']
        labels = {
            'content': '본문',
        }

# Comment 생성 및 수정시 사용 form
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ['content']
        labels = {
            'content': '댓글',
        }

        
# Article 삭제시 사용 form
class ArticleDeleteConfirmationForm(forms.Form):
    confirmation_string = forms.CharField()

    def __init__(self, *args, **kwargs):
        self.article_title = kwargs.pop('article_title')
        super(ArticleDeleteConfirmationForm, self).__init__(*args, **kwargs)

    def clean_confirmation_string(self):
        data = self.cleaned_data['confirmation_string']
        if self.article_title != data:
            raise forms.ValidationError("확인문자가 일치하지 않습니다.")

        return data  

wiki/views/article_views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from ..forms import ArticleCreateForm, ArticleEditForm, ArticleDeleteConfirmationForm
from ..models import Article

@login_required(login_url='common:login')
def article_create(request):
    if request.method == 'POST':
        # TODO: 중복 title 가지는 article 생성 방지 logic 구현
        form = ArticleCreateForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.create_date = timezone.now()
            article.recent_edit_date = timezone.now()
            article.save()
            return redirect('wiki:article', article_title=article.title)
    else:
        form = ArticleCreateForm()
        try:
            form.fields['title'].initial = request.GET.get('q')
        except:
            pass
    context = {'title': '새 문서', 'form': form}
    return render(request, 'wiki/article_form_create.html', context)


@login_required(login_url='common:login')
def article_edit(request, article_title):
    article = get_object_or_404(Article, title=article_title)
    if request.method == 'POST':
        form = ArticleEditForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.recent_edit_date = timezone.now()
            article.save()
            return redirect('wiki:article', article_title=article.title)
    else:
       form = ArticleEditForm(instance=article)
    context = {'title': '편집: '+article_title, 'form': form, 'article_title': article_title} 
    return render(request, 'wiki/article_form_edit.html', context)

@login_required(login_url='common:login')
def article_delete(request, article_title):
    article = get_object_or_404(Article, title=article_title)
    if request.method == "POST":
        form = ArticleDeleteConfirmationForm(request.POST, article_title=article_title)
        if form.is_valid():
            article.delete()
            return redirect('wiki:articles')
    else:
        form = ArticleDeleteConfirmationForm(article_title=article_title)

    context = {'title': '삭제: '+article_title, 'article': article, 'form': form}
    return render(request, 'wiki/article_form_delete.html', context)

wiki/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Article
import random

def index(request):
    return redirect('wiki:main_page')


def articles(request):
    page = request.GET.get('page', '1')
    article_list = Article.objects.order_by('-recent_edit_date')
    paginator = Paginator(article_list, 10)
    page_obj = paginator.get_page(page)
    context = {'title': '최근 변경내역', 'article_list': page_obj}
    return render(request, 'wiki/article_list.html', context)


def article(request, article_title):
    try:
        article = Article.objects.get(title=article_title)
        context = {'title': article_title, 'article': article}
        return render(request, 'wiki/article.html', context)
    except Article.DoesNotExist:
        context = {'title': article_title, 'article_title': article_title}
        return render(request, 'wiki/article_empty.html', context)



def article_search(request):
    # TODO: search 로직 수정필요
    query_article_title = request.GET.get('q')
    try:
        article = Article.objects.get(title=query_article_title)
        return redirect('wiki:article', article_title=article.title)
    except:
        context = {'title': '검색', 'query_name': query_article_title}
        return render(request, 'wiki/article_search.html', context)


def main_page(request):
    intro = Article.objects.get(title="_Alkorithms 소개")
    etc = Article.objects.get(title="_기타 문서")
    emaxx_proj = Article.objects.get(title="_E-maxx Algorithms 한국어 현지화 프로젝트")

    # motd list, must be seperated
    motd = ['$P$는 $NP$가 아닙니다', '$O(N^2)$ 보단 $O(NlogN)$, $O(NlogN)$ 보단 $O(N)$', '자매품인 Data strucktures 도 만나보세요', '앨런 튜링 vs 폰 노이만', 'Codechef Ninjas haters', 'Algorithms 와는 다릅니다', 'Built with Django']

    context = {'title': '대문', 'intro': intro, 'etc': etc, 'emaxx_proj': emaxx_proj, 'motd': random.choice(motd)}
    return render(request, 'wiki/main_page.html', context)

wiki/views/comment_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import HttpResponseNotAllowed
from ..forms import CommentForm
from ..models import Article, Comment

@login_required(login_url='common:login')
def comment_create(request, article_title):
    article = get_object_or_404(Article, title=article_title)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            try:
                comment.author = request.user
            except:
                pass
            comment.article = article
            comment.save()
            return redirect('wiki:article', article_title=article.title)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')

    context = {'article': article, 'form': form}
    return render(request, 'wiki/article.html', context)

@login_required(login_url='common:login')
def comment_delete(request, article_title, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.method == "POST":
        if request.user == comment.author:
            comment.delete()
            return redirect('wiki:article', article_title=article_title)
        else:
            # TODO: 본인이 author 가 아닌 comment를 삭제하려고 시도할때 처리 로직
            pass
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    

templates/wiki/article.html
{% extends 'layout.html' %}
{% load wiki_filter %}
{% block content %}
<!-- Article -->
<div class="d-flex justify-content-between border-bottom py-2">
    <!-- <h2><a href=".">{{ article.title }}</a></h2> -->
    <h2>{{ article.title }}</h2>
    <div class="d-grid gap-2 d-md-flex">
        <div class="d-grid gap-2 d-md-block">
            <a class="btn btn-primary" type="button" role="button" href="{% url 'wiki:article_edit' article.title %}">Edit</a>
            <a class="btn btn-primary disabled" type="button" role="button" href="history">History</a>
        </div>
    </div>
</div>

<div class="card my-3">
    <div class="card-body">
        <div class="card-text">{{ article.content|mark }}</div>
    </div>
</div>

<h5 class="border-bottom my-3 py-2">{{article.comment_set.count}}개의 리뷰가 있습니다.</h5>
{% for comment in article.comment_set.all %}
<div class="card my-3">
    <div class="card-header d-flex justify-content-between align-items-center">
        <div>
            {% if comment.author %}
            {{ comment.author.username }}
            {% else %}
            Anonymous
            {% endif %}
            ({{ comment.create_date }})
        </div>
        <div>
            {% if user == comment.author %}
            <form action="{% url 'wiki:comment_delete' article.title comment.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Delete" class="btn btn-sm btn-danger">
            </form>
            {% endif %}
        </div>
    </div>
    <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>    
    </div>
</div>
{% endfor %}

<form action="{% url 'wiki:comment_create' article.title %}" method="post" class="my-3">
    {% csrf_token %}
    <div class="mb-3">
        <label for="content" class="form-label">Comment 입력</label>
        {% if form.content.errors %}
        <textarea name="content" id="content" class="form-control is-invalid" rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        <div id="contentHelpBlock" class="invalid-feedback">
            {{ form.content.errors }}
        </div>
        {% else %}
        <textarea name="content" id="content" class="form-control"  rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        {% endif %}        
    </div>
    <input type="submit" value="Comment 등록" class="btn btn-primary">
</form>
{% include "../katex.html" %}
{% endblock %}

templates/wiki/article_empty.html
{% extends 'layout.html' %}

{% block content %}
<!-- Article -->
<div class="d-flex justify-content-between border-bottom py-2">
    <h2>{{ article_title }}</h2>
</div>
<div class="card my-3">
    <div class="card-body">
        <div class="card-text">
            <p>{{ article_title }} 문서가 존재하지 않습니다.</p>
            <form class="d-flex" id="create_with_name" method="get" action="{% url 'wiki:article_create' %}">
                <input type="hidden" id="q" name="q" value="{{ article_title }}">
                <button class="btn btn-success" type="submit">{{ article_title }} 문서 새로 작성하기</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/wiki/article_form_create.html
{% extends 'layout.html' %}

{% block content %}
<h2 class="justify-content-between border-bottom py-2">아티클 등록</h2>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="title" class="form-label">제목</label>
        {% if form.title.errors %}
        <input type="text" class="form-control is-invalid" name="title" id="title" value="{{ form.title.value|default_if_none:'' }}">
        <div id="titleHelpBlock" class="invalid-feedback">
            {{ form.title.errors }}
        </div>
        {% else %}
        <input type="text" class="form-control" name="title" id="title" value="{{ form.title.value|default_if_none:'' }}">
        {% endif %}
    </div>
    <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        {% if form.content.errors %}
        <textarea class="form-control is-invalid" name="content"
            id="content" rows="20">{{ form.content.value|default_if_none:'' }}</textarea>
        <div id="contentHelpBlock" class="invalid-feedback">
            {{ form.content.errors }}
        </div>
        {% else %}
        <textarea class="form-control" name="content"
            id="content" rows="20">{{ form.content.value|default_if_none:'' }}</textarea>
        {% endif %}            
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
</form>
{% endblock %}

templates/wiki/article_form_delete.html
{% extends 'layout.html' %}

{% block content %}
<h2 class="border-bottom py-2">Delete: {{ article.title }}</h2>
<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="confirmation_string" class="form-label">Article 삭제 확인</label>
        {% if form.confirmation_string.errors %}
        <input type="text" class="form-control is-invalid" name="confirmation_string" id="confirmation_string">
        <div id="confirmHelpBlock" class="invalid-feedback">
            Article을 삭제하려면 article 제목을 정확히 입력하세요.
        </div>
        {% else %}
        <input type="text" class="form-control" name="confirmation_string" id="confirmation_string">
        <div id="confirmHelpBlock" class="form-text">
            Article을 삭제하려면 article 제목을 정확히 입력하세요.
        </div>
        {% endif %}        
    </div>
    <button type="submit" class="btn btn-danger">Delete</button>
</form>
{% endblock %}

templates/wiki/article_form_edit.html
{% extends 'layout.html' %}

{% block content %}
<div class="d-flex justify-content-between border-bottom py-2">
    <h2>Edit: {{ article_title }}</h2>
    <div class="d-grip gap-2 d-md-flex">
        <div class="d-grid gap-2 d-md-block">
            <a class="btn btn-danger" type="button" role="button" href="{% url 'wiki:article_delete' article_title %}">Delete</a>
        </div>
    </div>
</div>

<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="content" class="form-label">내용</label>
        {% if form.content.errors %}
        <textarea class="form-control is-invalid" name="content"
            id="content" rows="20">{{ form.content.value|default_if_none:'' }}</textarea>
        <div id="contentHelpBlock" class="invalid-feedback">
            {{ form.content.errors }}
        </div>
        {% else %}
        <textarea class="form-control" name="content"
        id="content" rows="20">{{ form.content.value|default_if_none:'' }}</textarea>
        {% endif %}  
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
</form>
{% endblock %}

templates/wiki/article_list.html
{% extends 'layout.html' %}
{% load wiki_filter %}
{% block content %}
<h2 class="border-bottom py-2">Recent changes</h2>
<table class="table">
    <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>최근변경일자</th>
        </tr>
    </thead>
    <tbody>
        {% if article_list %}
        {% for article in article_list %}
        <tr>
            <td>
                {{ article_list.paginator.count|sub:article_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'wiki:article' article.title %}">{{ article.title }}</a>
            </td>
            <td>{{ article.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">Article이 없습니다.</td>
        </tr>
        {% endif %}
    </tbody>
</table>
<ul class="pagination justify-content-center">
    {% if article_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ article_list.previous_page_number }}">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
    </li>
    {% endif %}
    {% for page_number in article_list.paginator.page_range %}
    {% if page_number >= article_list.number|add:-5 and page_number <= article_list.number|add:5 %}
    {% if page_number == article_list.number %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endif %}
    {% endfor %}
    {% if article_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ article_list.next_page_number }}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
</ul>
<a href="{% url 'wiki:article_create' %}" class="btn btn-primary">Article 작성하기</a>
{% endblock %}

templates/wiki/article_search.html
{% extends 'layout.html' %}

{% block content %}
<h2 class="justify-content-between border-bottom py-2">Article search: {{ query_name }}</h2>

<div class="alert alert-warning" role="alert">
    <h3>NOT IMPLEMENTED YET !</h3>
    <p>이름이 정확히 일치하는 article이 없을시 표시되는 페이지 입니다.</p>
</div>
{% endblock %}

templates/wiki/main_page.html
{% extends 'layout.html' %}
{% load wiki_filter %}
{% block content %}
<h2 class="justify-content-between border-bottom py-2">대문</h2>

<div class="card mb-3">
    <div class="card-body">
        <h1 class="card-title mb-3">Alkorithms에 오신것을 환영합니다!</h5>
        <p class="card-text">{{ motd }}</p>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="card mb-3">
            <div class="card-header">Alkorithms는...</div>
            <div class="card-body">
                <div class="card-text">{{ intro.content|mark }}</div>
                <h5 class="card-title">이런, 찾는 문서가 없으세요?</h5>
                <a href="{% url 'wiki:article_create' %}" class="btn btn-primary">새 문서 작성하기</a>
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">E-maxx Algorithms 한국어 현지화 프로젝트</div>
            <div class="card-body">
                <div class="card-text">{{ emaxx_proj.content|mark }}</div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="card mb-3">
            <div class="card-header">재미없는 문서</div>
            <div class="card-body">
                <div class="card-text">{{ etc.content|mark }}</div>
            </div>
        </div>
        <div class="card mb">
            <div class="card-header">변경 사항</div>
            <div class="card-body">
                이곳에 업데이트 내용이 표시될 것입니다.
            </div>
        </div>
    </div>
</div>

{% include "katex.html" %}
{% endblock %}