common/urls.py
from django.urls import path
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('sign-up/', views.signup, name='signup'),
    path('settings/', views.settings, name='settings'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='wiki/')),
    path('common/', include('common.urls')),
    path('wiki/', include('wiki.urls')),
    path('admin/', admin.site.urls),
]

handler404 = 'common.views.page_not_found'

wiki/urls.py
from django.urls import path
from .views import base_views, article_views, comment_views

app_name = 'wiki'

urlpatterns = [
    # views/base_views
    path('', base_views.index, name='index'),
    path('main_page/', base_views.main_page, name='main_page'),
    path('articles/', base_views.articles, name='articles'),
    path('search/', base_views.article_search, name='article_search'),
    path('new_article/', article_views.article_create, name='article_create'),

    path('<str:article_title>/', base_views.article, name='article'),
    path('<str:article_title>/edit/', article_views.article_edit, name='article_edit'),
    path('<str:article_title>/delete/', article_views.article_delete, name='article_delete'),
    path('<str:article_title>/new_comment/', comment_views.comment_create, name='comment_create'),
    path('<str:article_title>/comments/<str:comment_id>', comment_views.comment_delete, name='comment_delete'),
]

templates/form_error.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}

    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>: {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}

    {% for error in form.non_field_errors %}
    <div>
        {{ error }}
    </div>
    {% endfor %}
</div>
{% endif %}

templates/google_analytics.html
{% load env_extras %}
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id={% get_env_var 'GOOGLE_ANALYTICS_ID' %}"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', "{% get_env_var 'GOOGLE_ANALYTICS_ID' %}");
</script>

templates/katex.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css" integrity="sha384-KiWOvVjnN8qwAZbuQyWDIbfCLFhLXNETzBQjA/92pIowpC0d2O3nppDGQVgwd2nB" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js" integrity="sha384-0fdwu/T/EQMsQlrHCCHoH10pkPLlKA1jL5dFyUOvB3lfeT2540/2g6YgSi2BL14p" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
<script>
    document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
              {left: '$$', right: '$$', display: true},
              {left: '$', right: '$', display: false},
              {left: '\\(', right: '\\)', display: false},
              {left: '\\[', right: '\\]', display: true}
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
    });
</script>

templates/layout.html
{% load static %}

<!doctype html>
<html lang="ko">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

	<!-- custom CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

	{% include "google_analytics.html" %}

	{% if title %}
	<title>{{title}} - Alkorithms</title>
	{% else %}
	<title>Alkorithms</title>
	{% endif %}
</head>

<body>
	{% include "navbar.html" %}
	<div class="container my-3">
		{% block content %}
		{% endblock %}
	</div>
	<footer class="my-5 pt-5 text-muted text-center text-small">
		<p class="mb-1">Made by ASIXER</p>
		<ul class="list-inline">
			<li class="list-inline-item"><a href="https://github.com/SylvesterKwon/marki">Github</a></li>
			<li class="list-inline-item"><a href="https://discord.com/invite/rs2q8qPv6z">Discord</a></li>
		</ul>
	</footer>
</body>
<script src="{% static 'bootstrap.min.js' %}"></script>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/wiki">Alkorithms</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'wiki:articles' %}">최근 변경</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        특수 기능
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">미구현</a></li>
                    </ul>
                </li>
            
            </ul>
            <div class="d-flex gap-2">
                <div class="d-flex gap-2">
                    {% if user.is_authenticated %}
                    <div class="nav-item dropdown">
                        <button class="btn btn-secondary dropdown-toggle" id="userDropdown"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </button>
                        <ul class="dropdown-menu"></a>
                            <li><a class="dropdown-item" href="{% url 'common:settings' %}"> 설정</a></li>
                            <li><a class="dropdown-item" href="#"> 사용자 문서 (미구현)</a></li>
                            <li><a class="dropdown-item" href="#"> 기여 내역 (미구현)</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            {% if user.is_staff %}
                            <li><a class="dropdown-item text-danger" href="/admin">Admin</a></li>
                            {% endif %}
                            <li><a class="dropdown-item text-danger" href="{% url 'common:logout' %}">Log out</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'common:login' %}">Login</a>
                    <a class="btn btn-secondary" href="{% url 'common:signup' %}">Sign up</a>
                    {% endif %}
                </div>
                <form class="d-flex" id="search_form" method="get" action="{% url 'wiki:article_search' %}">
                    <input class="form-control me-2" id="search_kw" name="q" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
</nav>